repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort

  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8

  - repo:  https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        additional_dependencies:
          - tokenize-rt==3.2.0
          - sqlalchemy-stubs==v0.3
        files: (^tests/)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
